# Numpy Arrays

In [1]:
# one dimension vector(array), or
# two dimension matrix

In [2]:
my_list=[1,2,3]

In [6]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [12]:
# transform normal python list to numpy array

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
mat = np.array(my_mat)

In [11]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
# Create a numpy array

In [ ]:
np.arange()

In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [17]:
# Generate an array of all 0s

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# np.linspace() creates contents within given range and given intervals

In [22]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [26]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [ ]:
# Create Identity Matrix

In [27]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# Random Libraries

In [28]:
# Uniform distribution
np.random.rand(5)

array([0.58363836, 0.70968977, 0.51291318, 0.67872361, 0.44114121])

In [29]:
np.random.rand(5,5)

array([[0.88768319, 0.40556084, 0.76089028, 0.2521472 , 0.82525009],
       [0.0291708 , 0.95604819, 0.4102761 , 0.98010098, 0.65277543],
       [0.43933177, 0.99420218, 0.44865976, 0.60552836, 0.6383884 ],
       [0.21166136, 0.32805454, 0.66829978, 0.99978734, 0.17380801],
       [0.90687927, 0.64016003, 0.96436287, 0.45023855, 0.47743538]])

In [41]:
# Normal distribution center around 0
np.random.randn(4)

array([ 0.36415526, -0.27687837, -0.21916569,  0.53692457])

In [40]:
np.random.randn(4,4)

array([[ 0.25362095,  0.47246896,  1.05246613, -0.60963917],
       [ 0.89638891, -0.00492949, -0.28517231,  1.40331107],
       [-0.21475833, -1.63619005,  0.26432616,  0.58226644],
       [-2.28291529,  0.06355832, -2.30260445, -0.38440347]])

In [42]:
# Create Random integers with range
np.random.randint(1,100)

53

In [43]:
np.random.randint(1,100,5)

array([63, 36, 75, 87, 86])

# Some Useful Attributes and Methods

In [35]:
arr = np.arange(25)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
ranarr = np.random.randint(0,50,10)

In [38]:
ranarr

array([19, 41,  5, 36, 43, 24, 23, 31, 42, 18])

In [47]:
# Reshape Method
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [117]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [49]:
ranarr

array([19, 41,  5, 36, 43, 24, 23, 31, 42, 18])

In [50]:
# Find Maximum/Minimum Value in the Array
ranarr.max()

43

In [51]:
ranarr.min()

5

In [52]:
# Find the index location of max/min
ranarr.argmax()

4

In [53]:
ranarr.argmin()

2

In [55]:
# Return the shape of an array
arr.shape

(25,)

In [57]:
arr.reshape(5,5).shape

(5, 5)

In [58]:
# Data Type of an array
arr.dtype

dtype('int32')

In [59]:
# Shorten certain random operation
from numpy.random import randint

In [60]:
randint(2,10)

6

# Numpy Indexing and Selection

In [63]:
arr = np.arange(0,11)

In [64]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr[8]

8

In [67]:
arr[1:5]

array([1, 2, 3, 4])

In [69]:
arr[:5]

array([0, 1, 2, 3, 4])

In [70]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [71]:
arr[2::]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
arr[::9]

array([0, 9])

In [96]:
# Slicing Array

In [80]:
arr[0:5] = 100

In [81]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [93]:
arr = np.arange(0,11)

In [92]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [84]:
slice_of_arr = arr[0:6]

In [85]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [90]:
slice_of_arr[:] = 99

In [91]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [87]:
# Copy an array, but not referencing an array

In [94]:
arr_copy = arr.copy()

In [95]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Indexing in Matrix

In [98]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [99]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [100]:
arr_2d[0][0]

5

In [106]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

# Conditional Selection

In [107]:
arr = np.arange(1,11)

In [108]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
bool_arr = arr > 5

In [110]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [111]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [113]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [114]:
arr[arr<3]

array([1, 2])

In [116]:
arr[arr<=3]

array([1, 2, 3])

In [119]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [120]:
arr_2d[1:3,]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [122]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])

# Numpy Operations

In [123]:
arr = np.arange(0,11)

In [124]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [125]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [126]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [127]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [128]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [129]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [131]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [133]:
arr / arr

C:\Users\SungI7\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [134]:
arr / 0

C:\Users\SungI7\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\SungI7\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

# Universal Array Functions

In [135]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [136]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [137]:
np.max(arr)

10

In [138]:
np.min(arr)

0

In [139]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [140]:
np.log(arr)

C:\Users\SungI7\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [ ]:
# https://docs.scipy.org/doc/numpy/reference/ufuncs.html